version: "2"

run:
  timeout: 5m
  go: "1.24"
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - whitespace
    - err113
    - errorlint
    - nilerr
    - gocritic
    - nakedret
    - unconvert
    - dogsled
    - copyloopvar
    - prealloc
    - gosec
    - exhaustive
    - noctx
    - nolintlint
    - promlinter

formatters:
  enable:
    - gofmt
    - goimports
    - gci

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - revive

output:
  format: colored-line-number
  print-linter-name: true
  sort-results: true