version: "2"

linters:
  enable:
    - copyloopvar      # Check loop variable copying
    - dogsled          # Check blank identifier assignments
    - err113           # Check error handling best practices
    - errorlint        # Check error wrapping and unwrap
    - exhaustive       # Check switch statement completeness
    - gocritic         # Various Go code improvement suggestions
    - goprintffuncname # Check printf-style function names
    - gosec           # Security checks
    - misspell        # Check spelling errors
    - nakedret        # Check naked returns
    - nilerr          # Check nil error returns
    - noctx           # Check context usage
    - nolintlint      # Check nolint directive usage
    - prealloc        # Check pre-allocatable slices
    - promlinter      # Prometheus metrics checks
    - revive          # Go code style checks
    - unconvert       # Check unnecessary type conversions
    - whitespace      # Check whitespace

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true  # Allow unused parameters (common in interface implementations)
      - name: exported
        disabled: true  # Allow unexported types for internal use
      - name: package-comments
        disabled: true  # Allow packages without comments

issues:
  max-issues-per-linter: 0  # No limit per linter
  max-same-issues: 0        # No limit for same issues
  
  exclude-rules:
    # Test file exceptions
    - path: _test\.go
      linters:
        - funlen            # Test functions may be longer
        - gochecknoglobals  # Tests may use globals
        - gosec             # Security exceptions in tests
        - noctx             # Context usage more flexible in tests
        - revive            # Relaxed code style in tests

  exclude-dirs:
    - third_party     # Exclude third-party code
    - builtin         # Exclude builtin code
    - examples        # Exclude example code

run:
  timeout: 10m